/*
 * EJBCA REST Interface
 * API reference documentation.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.trustable.ca3s.core.service.dto.ejbca;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * CaInfosRestResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-27T11:17:53.164838525Z[GMT]")

public class CaInfosRestResponse {
  @SerializedName("certificate_authorities")
  private List<CaInfoRestResponse> certificateAuthorities = null;

  public CaInfosRestResponse certificateAuthorities(List<CaInfoRestResponse> certificateAuthorities) {
    this.certificateAuthorities = certificateAuthorities;
    return this;
  }

  public CaInfosRestResponse addCertificateAuthoritiesItem(CaInfoRestResponse certificateAuthoritiesItem) {
    if (this.certificateAuthorities == null) {
      this.certificateAuthorities = new ArrayList<CaInfoRestResponse>();
    }
    this.certificateAuthorities.add(certificateAuthoritiesItem);
    return this;
  }

   /**
   * Get certificateAuthorities
   * @return certificateAuthorities
  **/
  @Schema(description = "")
  public List<CaInfoRestResponse> getCertificateAuthorities() {
    return certificateAuthorities;
  }

  public void setCertificateAuthorities(List<CaInfoRestResponse> certificateAuthorities) {
    this.certificateAuthorities = certificateAuthorities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaInfosRestResponse caInfosRestResponse = (CaInfosRestResponse) o;
    return Objects.equals(this.certificateAuthorities, caInfosRestResponse.certificateAuthorities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificateAuthorities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaInfosRestResponse {\n");

    sb.append("    certificateAuthorities: ").append(toIndentedString(certificateAuthorities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
