/*
 * EJBCA REST Interface
 * API reference documentation.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.trustable.ca3s.core.service.dto.ejbca;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * CertificatesRestResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-27T11:17:53.164838525Z[GMT]")

public class CertificatesRestResponse {
  @JsonProperty("certificates")
  private List<CertificateRestResponse> certificates = null;

  public CertificatesRestResponse certificates(List<CertificateRestResponse> certificates) {
    this.certificates = certificates;
    return this;
  }

  public CertificatesRestResponse addCertificatesItem(CertificateRestResponse certificatesItem) {
    if (this.certificates == null) {
      this.certificates = new ArrayList<CertificateRestResponse>();
    }
    this.certificates.add(certificatesItem);
    return this;
  }

   /**
   * Get certificates
   * @return certificates
  **/
  @Schema(description = "")
  public List<CertificateRestResponse> getCertificates() {
    return certificates;
  }

  public void setCertificates(List<CertificateRestResponse> certificates) {
    this.certificates = certificates;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificatesRestResponse certificatesRestResponse = (CertificatesRestResponse) o;
    return Objects.equals(this.certificates, certificatesRestResponse.certificates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificatesRestResponse {\n");

    sb.append("    certificates: ").append(toIndentedString(certificates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
