/*
 * EJBCA REST Interface
 * API reference documentation.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.trustable.ca3s.core.service.dto.ejbca;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * CertificateRequestRestRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-27T11:17:53.164838525Z[GMT]")

public class CertificateRequestRestRequest {
  @JsonProperty("certificate_request")
  private String certificateRequest = null;

  @JsonProperty("username")
  private String username = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("include_chain")
  private Boolean includeChain = null;

  @JsonProperty("certificate_authority_name")
  private String certificateAuthorityName = null;

  public CertificateRequestRestRequest certificateRequest(String certificateRequest) {
    this.certificateRequest = certificateRequest;
    return this;
  }

   /**
   * Certificate request
   * @return certificateRequest
  **/
  @Schema(example = "MIICh...V8shQ== OR -----BEGIN CERTIFICATE REQUEST----- MIICh...V8shQ== -----END CERTIFICATE REQUEST-----", description = "Certificate request")
  public String getCertificateRequest() {
    return certificateRequest;
  }

  public void setCertificateRequest(String certificateRequest) {
    this.certificateRequest = certificateRequest;
  }

  public CertificateRequestRestRequest username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Username
   * @return username
  **/
  @Schema(example = "JohnDoe", description = "Username")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public CertificateRequestRestRequest password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Password
   * @return password
  **/
  @Schema(example = "foo123", description = "Password")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public CertificateRequestRestRequest includeChain(Boolean includeChain) {
    this.includeChain = includeChain;
    return this;
  }

   /**
   * Get includeChain
   * @return includeChain
  **/
  @Schema(description = "")
  public Boolean isIncludeChain() {
    return includeChain;
  }

  public void setIncludeChain(Boolean includeChain) {
    this.includeChain = includeChain;
  }

  public CertificateRequestRestRequest certificateAuthorityName(String certificateAuthorityName) {
    this.certificateAuthorityName = certificateAuthorityName;
    return this;
  }

   /**
   * Certificate Authority (CA) name
   * @return certificateAuthorityName
  **/
  @Schema(example = "ExampleCA", description = "Certificate Authority (CA) name")
  public String getCertificateAuthorityName() {
    return certificateAuthorityName;
  }

  public void setCertificateAuthorityName(String certificateAuthorityName) {
    this.certificateAuthorityName = certificateAuthorityName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateRequestRestRequest certificateRequestRestRequest = (CertificateRequestRestRequest) o;
    return Objects.equals(this.certificateRequest, certificateRequestRestRequest.certificateRequest) &&
        Objects.equals(this.username, certificateRequestRestRequest.username) &&
        Objects.equals(this.password, certificateRequestRestRequest.password) &&
        Objects.equals(this.includeChain, certificateRequestRestRequest.includeChain) &&
        Objects.equals(this.certificateAuthorityName, certificateRequestRestRequest.certificateAuthorityName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificateRequest, username, password, includeChain, certificateAuthorityName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateRequestRestRequest {\n");

    sb.append("    certificateRequest: ").append(toIndentedString(certificateRequest)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    includeChain: ").append(toIndentedString(includeChain)).append("\n");
    sb.append("    certificateAuthorityName: ").append(toIndentedString(certificateAuthorityName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
