/*
 * EJBCA REST Interface
 * API reference documentation.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.trustable.ca3s.core.service.dto.ejbca;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * CertificateRestResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-27T11:17:53.164838525Z[GMT]")

public class CertificateRestResponse {
  @SerializedName("certificate")
  private List<byte[]> certificate = null;

  @SerializedName("serial_number")
  private String serialNumber = null;

  @SerializedName("response_format")
  private String responseFormat = null;

  @SerializedName("certificate_chain")
  private List<List<byte[]>> certificateChain = null;

  @SerializedName("certificate_profile")
  private String certificateProfile = null;

  @SerializedName("end_entity_profile")
  private String endEntityProfile = null;

  public CertificateRestResponse certificate(List<byte[]> certificate) {
    this.certificate = certificate;
    return this;
  }

  public CertificateRestResponse addCertificateItem(byte[] certificateItem) {
    if (this.certificate == null) {
      this.certificate = new ArrayList<byte[]>();
    }
    this.certificate.add(certificateItem);
    return this;
  }

   /**
   * Certificate
   * @return certificate
  **/
  @Schema(example = "MIIDXzCCA...eW1Zro0=", description = "Certificate")
  public List<byte[]> getCertificate() {
    return certificate;
  }

  public void setCertificate(List<byte[]> certificate) {
    this.certificate = certificate;
  }

  public CertificateRestResponse serialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * Hex Serial Number
   * @return serialNumber
  **/
  @Schema(example = "1234567890ABCDEF", description = "Hex Serial Number")
  public String getSerialNumber() {
    return serialNumber;
  }

  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }

  public CertificateRestResponse responseFormat(String responseFormat) {
    this.responseFormat = responseFormat;
    return this;
  }

   /**
   * Response format
   * @return responseFormat
  **/
  @Schema(example = "DER", description = "Response format")
  public String getResponseFormat() {
    return responseFormat;
  }

  public void setResponseFormat(String responseFormat) {
    this.responseFormat = responseFormat;
  }

  public CertificateRestResponse certificateChain(List<List<byte[]>> certificateChain) {
    this.certificateChain = certificateChain;
    return this;
  }

  public CertificateRestResponse addCertificateChainItem(List<byte[]> certificateChainItem) {
    if (this.certificateChain == null) {
      this.certificateChain = new ArrayList<List<byte[]>>();
    }
    this.certificateChain.add(certificateChainItem);
    return this;
  }

   /**
   * Certificate chain
   * @return certificateChain
  **/
  @Schema(example = "[\"ABC123efg...345xyz0=\"]", description = "Certificate chain")
  public List<List<byte[]>> getCertificateChain() {
    return certificateChain;
  }

  public void setCertificateChain(List<List<byte[]>> certificateChain) {
    this.certificateChain = certificateChain;
  }

  public CertificateRestResponse certificateProfile(String certificateProfile) {
    this.certificateProfile = certificateProfile;
    return this;
  }

   /**
   * Certificate profile name
   * @return certificateProfile
  **/
  @Schema(example = "ENDUSER", description = "Certificate profile name")
  public String getCertificateProfile() {
    return certificateProfile;
  }

  public void setCertificateProfile(String certificateProfile) {
    this.certificateProfile = certificateProfile;
  }

  public CertificateRestResponse endEntityProfile(String endEntityProfile) {
    this.endEntityProfile = endEntityProfile;
    return this;
  }

   /**
   * End Entity profile name
   * @return endEntityProfile
  **/
  @Schema(example = "ExampleEEP", description = "End Entity profile name")
  public String getEndEntityProfile() {
    return endEntityProfile;
  }

  public void setEndEntityProfile(String endEntityProfile) {
    this.endEntityProfile = endEntityProfile;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateRestResponse certificateRestResponse = (CertificateRestResponse) o;
    return Objects.equals(this.certificate, certificateRestResponse.certificate) &&
        Objects.equals(this.serialNumber, certificateRestResponse.serialNumber) &&
        Objects.equals(this.responseFormat, certificateRestResponse.responseFormat) &&
        Objects.equals(this.certificateChain, certificateRestResponse.certificateChain) &&
        Objects.equals(this.certificateProfile, certificateRestResponse.certificateProfile) &&
        Objects.equals(this.endEntityProfile, certificateRestResponse.endEntityProfile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificate, serialNumber, responseFormat, certificateChain, certificateProfile, endEntityProfile);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateRestResponse {\n");

    sb.append("    certificate: ").append(toIndentedString(certificate)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    responseFormat: ").append(toIndentedString(responseFormat)).append("\n");
    sb.append("    certificateChain: ").append(toIndentedString(certificateChain)).append("\n");
    sb.append("    certificateProfile: ").append(toIndentedString(certificateProfile)).append("\n");
    sb.append("    endEntityProfile: ").append(toIndentedString(endEntityProfile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
