/*
 * EJBCA REST Interface
 * API reference documentation.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.trustable.ca3s.core.service.dto.ejbca;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
/**
 * CreateCrlRestResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-27T11:17:53.164838525Z[GMT]")

public class CreateCrlRestResponse {
  @JsonProperty("issuer_dn")
  private String issuerDn = null;

  @JsonProperty("latest_crl_version")
  private Integer latestCrlVersion = null;

  @JsonProperty("latest_delta_crl_version")
  private Integer latestDeltaCrlVersion = null;

  @JsonProperty("latest_partition_crl_versions")
  private Map<String, Integer> latestPartitionCrlVersions = null;

  @JsonProperty("latest_partition_delta_crl_versions")
  private Map<String, Integer> latestPartitionDeltaCrlVersions = null;

  @JsonProperty("all_success")
  private Boolean allSuccess = null;

  public CreateCrlRestResponse issuerDn(String issuerDn) {
    this.issuerDn = issuerDn;
    return this;
  }

   /**
   * Issuer Distinguished Name
   * @return issuerDn
  **/
  @Schema(example = "CN=ExampleCA", description = "Issuer Distinguished Name")
  public String getIssuerDn() {
    return issuerDn;
  }

  public void setIssuerDn(String issuerDn) {
    this.issuerDn = issuerDn;
  }

  public CreateCrlRestResponse latestCrlVersion(Integer latestCrlVersion) {
    this.latestCrlVersion = latestCrlVersion;
    return this;
  }

   /**
   * Latest base CRL version
   * @return latestCrlVersion
  **/
  @Schema(example = "10", description = "Latest base CRL version")
  public Integer getLatestCrlVersion() {
    return latestCrlVersion;
  }

  public void setLatestCrlVersion(Integer latestCrlVersion) {
    this.latestCrlVersion = latestCrlVersion;
  }

  public CreateCrlRestResponse latestDeltaCrlVersion(Integer latestDeltaCrlVersion) {
    this.latestDeltaCrlVersion = latestDeltaCrlVersion;
    return this;
  }

   /**
   * Latest delta CRL version
   * @return latestDeltaCrlVersion
  **/
  @Schema(example = "5", description = "Latest delta CRL version")
  public Integer getLatestDeltaCrlVersion() {
    return latestDeltaCrlVersion;
  }

  public void setLatestDeltaCrlVersion(Integer latestDeltaCrlVersion) {
    this.latestDeltaCrlVersion = latestDeltaCrlVersion;
  }

  public CreateCrlRestResponse latestPartitionCrlVersions(Map<String, Integer> latestPartitionCrlVersions) {
    this.latestPartitionCrlVersions = latestPartitionCrlVersions;
    return this;
  }

  public CreateCrlRestResponse putLatestPartitionCrlVersionsItem(String key, Integer latestPartitionCrlVersionsItem) {
    if (this.latestPartitionCrlVersions == null) {
      this.latestPartitionCrlVersions = new HashMap<String, Integer>();
    }
    this.latestPartitionCrlVersions.put(key, latestPartitionCrlVersionsItem);
    return this;
  }

   /**
   * Get latestPartitionCrlVersions
   * @return latestPartitionCrlVersions
  **/
  @Schema(description = "")
  public Map<String, Integer> getLatestPartitionCrlVersions() {
    return latestPartitionCrlVersions;
  }

  public void setLatestPartitionCrlVersions(Map<String, Integer> latestPartitionCrlVersions) {
    this.latestPartitionCrlVersions = latestPartitionCrlVersions;
  }

  public CreateCrlRestResponse latestPartitionDeltaCrlVersions(Map<String, Integer> latestPartitionDeltaCrlVersions) {
    this.latestPartitionDeltaCrlVersions = latestPartitionDeltaCrlVersions;
    return this;
  }

  public CreateCrlRestResponse putLatestPartitionDeltaCrlVersionsItem(String key, Integer latestPartitionDeltaCrlVersionsItem) {
    if (this.latestPartitionDeltaCrlVersions == null) {
      this.latestPartitionDeltaCrlVersions = new HashMap<String, Integer>();
    }
    this.latestPartitionDeltaCrlVersions.put(key, latestPartitionDeltaCrlVersionsItem);
    return this;
  }

   /**
   * Get latestPartitionDeltaCrlVersions
   * @return latestPartitionDeltaCrlVersions
  **/
  @Schema(description = "")
  public Map<String, Integer> getLatestPartitionDeltaCrlVersions() {
    return latestPartitionDeltaCrlVersions;
  }

  public void setLatestPartitionDeltaCrlVersions(Map<String, Integer> latestPartitionDeltaCrlVersions) {
    this.latestPartitionDeltaCrlVersions = latestPartitionDeltaCrlVersions;
  }

  public CreateCrlRestResponse allSuccess(Boolean allSuccess) {
    this.allSuccess = allSuccess;
    return this;
  }

   /**
   * Get allSuccess
   * @return allSuccess
  **/
  @Schema(description = "")
  public Boolean isAllSuccess() {
    return allSuccess;
  }

  public void setAllSuccess(Boolean allSuccess) {
    this.allSuccess = allSuccess;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateCrlRestResponse createCrlRestResponse = (CreateCrlRestResponse) o;
    return Objects.equals(this.issuerDn, createCrlRestResponse.issuerDn) &&
        Objects.equals(this.latestCrlVersion, createCrlRestResponse.latestCrlVersion) &&
        Objects.equals(this.latestDeltaCrlVersion, createCrlRestResponse.latestDeltaCrlVersion) &&
        Objects.equals(this.latestPartitionCrlVersions, createCrlRestResponse.latestPartitionCrlVersions) &&
        Objects.equals(this.latestPartitionDeltaCrlVersions, createCrlRestResponse.latestPartitionDeltaCrlVersions) &&
        Objects.equals(this.allSuccess, createCrlRestResponse.allSuccess);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issuerDn, latestCrlVersion, latestDeltaCrlVersion, latestPartitionCrlVersions, latestPartitionDeltaCrlVersions, allSuccess);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateCrlRestResponse {\n");

    sb.append("    issuerDn: ").append(toIndentedString(issuerDn)).append("\n");
    sb.append("    latestCrlVersion: ").append(toIndentedString(latestCrlVersion)).append("\n");
    sb.append("    latestDeltaCrlVersion: ").append(toIndentedString(latestDeltaCrlVersion)).append("\n");
    sb.append("    latestPartitionCrlVersions: ").append(toIndentedString(latestPartitionCrlVersions)).append("\n");
    sb.append("    latestPartitionDeltaCrlVersions: ").append(toIndentedString(latestPartitionDeltaCrlVersions)).append("\n");
    sb.append("    allSuccess: ").append(toIndentedString(allSuccess)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
