/*
 * EJBCA REST Interface
 * API reference documentation.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.trustable.ca3s.core.service.dto.ejbca;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * CrlRestResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-27T11:17:53.164838525Z[GMT]")

public class CrlRestResponse {
  @JsonProperty("crl")
  private List<byte[]> crl = null;

  @JsonProperty("response_format")
  private String responseFormat = null;

  public CrlRestResponse crl(List<byte[]> crl) {
    this.crl = crl;
    return this;
  }

  public CrlRestResponse addCrlItem(byte[] crlItem) {
    if (this.crl == null) {
      this.crl = new ArrayList<byte[]>();
    }
    this.crl.add(crlItem);
    return this;
  }

   /**
   * Certificate Revocation List (CRL)
   * @return crl
  **/
  @Schema(example = "MIIEV...SqQPE", description = "Certificate Revocation List (CRL)")
  public List<byte[]> getCrl() {
    return crl;
  }

  public void setCrl(List<byte[]> crl) {
    this.crl = crl;
  }

  public CrlRestResponse responseFormat(String responseFormat) {
    this.responseFormat = responseFormat;
    return this;
  }

   /**
   * Response format
   * @return responseFormat
  **/
  @Schema(example = "DER", description = "Response format")
  public String getResponseFormat() {
    return responseFormat;
  }

  public void setResponseFormat(String responseFormat) {
    this.responseFormat = responseFormat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CrlRestResponse crlRestResponse = (CrlRestResponse) o;
    return Objects.equals(this.crl, crlRestResponse.crl) &&
        Objects.equals(this.responseFormat, crlRestResponse.responseFormat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(crl, responseFormat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CrlRestResponse {\n");

    sb.append("    crl: ").append(toIndentedString(crl)).append("\n");
    sb.append("    responseFormat: ").append(toIndentedString(responseFormat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
