/*
 * EJBCA REST Interface
 * API reference documentation.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.trustable.ca3s.core.service.dto.ejbca;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * EnrollCertificateRestRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-27T11:17:53.164838525Z[GMT]")

public class EnrollCertificateRestRequest {
  @JsonProperty("certificate_request")
  private String certificateRequest = null;

  @JsonProperty("certificate_profile_name")
  private String certificateProfileName = null;

  @JsonProperty("end_entity_profile_name")
  private String endEntityProfileName = null;

  @JsonProperty("certificate_authority_name")
  private String certificateAuthorityName = null;

  @JsonProperty("username")
  private String username = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("account_binding_id")
  private String accountBindingId = null;

  @JsonProperty("include_chain")
  private Boolean includeChain = null;

  @JsonProperty("email")
  private String email = null;

  public EnrollCertificateRestRequest certificateRequest(String certificateRequest) {
    this.certificateRequest = certificateRequest;
    return this;
  }

   /**
   * Certificate request
   * @return certificateRequest
  **/
  @Schema(example = "MIICh...V8shQ== OR -----BEGIN CERTIFICATE REQUEST----- MIICh...V8shQ== -----END CERTIFICATE REQUEST-----", description = "Certificate request")
  public String getCertificateRequest() {
    return certificateRequest;
  }

  public void setCertificateRequest(String certificateRequest) {
    this.certificateRequest = certificateRequest;
  }

  public EnrollCertificateRestRequest certificateProfileName(String certificateProfileName) {
    this.certificateProfileName = certificateProfileName;
    return this;
  }

   /**
   * Certificate profile name
   * @return certificateProfileName
  **/
  @Schema(example = "ENDUSER", description = "Certificate profile name")
  public String getCertificateProfileName() {
    return certificateProfileName;
  }

  public void setCertificateProfileName(String certificateProfileName) {
    this.certificateProfileName = certificateProfileName;
  }

  public EnrollCertificateRestRequest endEntityProfileName(String endEntityProfileName) {
    this.endEntityProfileName = endEntityProfileName;
    return this;
  }

   /**
   * End Entity profile name
   * @return endEntityProfileName
  **/
  @Schema(example = "ExampleEEP", description = "End Entity profile name")
  public String getEndEntityProfileName() {
    return endEntityProfileName;
  }

  public void setEndEntityProfileName(String endEntityProfileName) {
    this.endEntityProfileName = endEntityProfileName;
  }

  public EnrollCertificateRestRequest certificateAuthorityName(String certificateAuthorityName) {
    this.certificateAuthorityName = certificateAuthorityName;
    return this;
  }

   /**
   * Certificate Authority (CA) name
   * @return certificateAuthorityName
  **/
  @Schema(example = "ExampleCA", description = "Certificate Authority (CA) name")
  public String getCertificateAuthorityName() {
    return certificateAuthorityName;
  }

  public void setCertificateAuthorityName(String certificateAuthorityName) {
    this.certificateAuthorityName = certificateAuthorityName;
  }

  public EnrollCertificateRestRequest username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Username
   * @return username
  **/
  @Schema(example = "JohnDoe", description = "Username")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public EnrollCertificateRestRequest password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Password
   * @return password
  **/
  @Schema(example = "foo123", description = "Password")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public EnrollCertificateRestRequest accountBindingId(String accountBindingId) {
    this.accountBindingId = accountBindingId;
    return this;
  }

   /**
   * Account Binding ID
   * @return accountBindingId
  **/
  @Schema(example = "1234567890", description = "Account Binding ID")
  public String getAccountBindingId() {
    return accountBindingId;
  }

  public void setAccountBindingId(String accountBindingId) {
    this.accountBindingId = accountBindingId;
  }

  public EnrollCertificateRestRequest includeChain(Boolean includeChain) {
    this.includeChain = includeChain;
    return this;
  }

   /**
   * Get includeChain
   * @return includeChain
  **/
  @Schema(description = "")
  public Boolean isIncludeChain() {
    return includeChain;
  }

  public void setIncludeChain(Boolean includeChain) {
    this.includeChain = includeChain;
  }

  public EnrollCertificateRestRequest email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email
   * @return email
  **/
  @Schema(example = "john.doe@example.com", description = "Email")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnrollCertificateRestRequest enrollCertificateRestRequest = (EnrollCertificateRestRequest) o;
    return Objects.equals(this.certificateRequest, enrollCertificateRestRequest.certificateRequest) &&
        Objects.equals(this.certificateProfileName, enrollCertificateRestRequest.certificateProfileName) &&
        Objects.equals(this.endEntityProfileName, enrollCertificateRestRequest.endEntityProfileName) &&
        Objects.equals(this.certificateAuthorityName, enrollCertificateRestRequest.certificateAuthorityName) &&
        Objects.equals(this.username, enrollCertificateRestRequest.username) &&
        Objects.equals(this.password, enrollCertificateRestRequest.password) &&
        Objects.equals(this.accountBindingId, enrollCertificateRestRequest.accountBindingId) &&
        Objects.equals(this.includeChain, enrollCertificateRestRequest.includeChain) &&
        Objects.equals(this.email, enrollCertificateRestRequest.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificateRequest, certificateProfileName, endEntityProfileName, certificateAuthorityName, username, password, accountBindingId, includeChain, email);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnrollCertificateRestRequest {\n");

    sb.append("    certificateRequest: ").append(toIndentedString(certificateRequest)).append("\n");
    sb.append("    certificateProfileName: ").append(toIndentedString(certificateProfileName)).append("\n");
    sb.append("    endEntityProfileName: ").append(toIndentedString(endEntityProfileName)).append("\n");
    sb.append("    certificateAuthorityName: ").append(toIndentedString(certificateAuthorityName)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    accountBindingId: ").append(toIndentedString(accountBindingId)).append("\n");
    sb.append("    includeChain: ").append(toIndentedString(includeChain)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
