/*
 * EJBCA REST Interface
 * API reference documentation.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.trustable.ca3s.core.service.dto.ejbca;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * ExpiringCertificatesRestResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-27T11:17:53.164838525Z[GMT]")

public class ExpiringCertificatesRestResponse {
  @SerializedName("pagination_rest_response_component")
  private PaginationRestResponseComponent paginationRestResponseComponent = null;

  @SerializedName("certificates_rest_response")
  private CertificatesRestResponse certificatesRestResponse = null;

  public ExpiringCertificatesRestResponse paginationRestResponseComponent(PaginationRestResponseComponent paginationRestResponseComponent) {
    this.paginationRestResponseComponent = paginationRestResponseComponent;
    return this;
  }

   /**
   * Get paginationRestResponseComponent
   * @return paginationRestResponseComponent
  **/
  @Schema(description = "")
  public PaginationRestResponseComponent getPaginationRestResponseComponent() {
    return paginationRestResponseComponent;
  }

  public void setPaginationRestResponseComponent(PaginationRestResponseComponent paginationRestResponseComponent) {
    this.paginationRestResponseComponent = paginationRestResponseComponent;
  }

  public ExpiringCertificatesRestResponse certificatesRestResponse(CertificatesRestResponse certificatesRestResponse) {
    this.certificatesRestResponse = certificatesRestResponse;
    return this;
  }

   /**
   * Get certificatesRestResponse
   * @return certificatesRestResponse
  **/
  @Schema(description = "")
  public CertificatesRestResponse getCertificatesRestResponse() {
    return certificatesRestResponse;
  }

  public void setCertificatesRestResponse(CertificatesRestResponse certificatesRestResponse) {
    this.certificatesRestResponse = certificatesRestResponse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpiringCertificatesRestResponse expiringCertificatesRestResponse = (ExpiringCertificatesRestResponse) o;
    return Objects.equals(this.paginationRestResponseComponent, expiringCertificatesRestResponse.paginationRestResponseComponent) &&
        Objects.equals(this.certificatesRestResponse, expiringCertificatesRestResponse.certificatesRestResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paginationRestResponseComponent, certificatesRestResponse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpiringCertificatesRestResponse {\n");

    sb.append("    paginationRestResponseComponent: ").append(toIndentedString(paginationRestResponseComponent)).append("\n");
    sb.append("    certificatesRestResponse: ").append(toIndentedString(certificatesRestResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
