/*
 * EJBCA REST Interface
 * API reference documentation.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.trustable.ca3s.core.service.dto.ejbca;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * KeyStoreRestRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-27T11:17:53.164838525Z[GMT]")

public class KeyStoreRestRequest {
  @SerializedName("username")
  private String username = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("key_alg")
  private String keyAlg = null;

  @SerializedName("key_spec")
  private String keySpec = null;

  public KeyStoreRestRequest username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Username
   * @return username
  **/
  @Schema(example = "JohnDoe", description = "Username")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public KeyStoreRestRequest password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Password
   * @return password
  **/
  @Schema(example = "foo123", description = "Password")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public KeyStoreRestRequest keyAlg(String keyAlg) {
    this.keyAlg = keyAlg;
    return this;
  }

   /**
   * Key algorithm used for enrollment
   * @return keyAlg
  **/
  @Schema(example = "RSA", description = "Key algorithm used for enrollment")
  public String getKeyAlg() {
    return keyAlg;
  }

  public void setKeyAlg(String keyAlg) {
    this.keyAlg = keyAlg;
  }

  public KeyStoreRestRequest keySpec(String keySpec) {
    this.keySpec = keySpec;
    return this;
  }

   /**
   * Key specification to use
   * @return keySpec
  **/
  @Schema(example = "4096", description = "Key specification to use")
  public String getKeySpec() {
    return keySpec;
  }

  public void setKeySpec(String keySpec) {
    this.keySpec = keySpec;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeyStoreRestRequest keyStoreRestRequest = (KeyStoreRestRequest) o;
    return Objects.equals(this.username, keyStoreRestRequest.username) &&
        Objects.equals(this.password, keyStoreRestRequest.password) &&
        Objects.equals(this.keyAlg, keyStoreRestRequest.keyAlg) &&
        Objects.equals(this.keySpec, keyStoreRestRequest.keySpec);
  }

  @Override
  public int hashCode() {
    return Objects.hash(username, password, keyAlg, keySpec);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeyStoreRestRequest {\n");

    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    keyAlg: ").append(toIndentedString(keyAlg)).append("\n");
    sb.append("    keySpec: ").append(toIndentedString(keySpec)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
