/*
 * EJBCA REST Interface
 * API reference documentation.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.trustable.ca3s.core.service.dto.ejbca;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * PaginationSummary
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-27T11:17:53.164838525Z[GMT]")

public class PaginationSummary {
  @SerializedName("page_size")
  private Integer pageSize = null;

  @SerializedName("current_page")
  private Integer currentPage = null;

  @SerializedName("total_certs")
  private Long totalCerts = null;

  public PaginationSummary pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @Schema(description = "")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public PaginationSummary currentPage(Integer currentPage) {
    this.currentPage = currentPage;
    return this;
  }

   /**
   * Get currentPage
   * @return currentPage
  **/
  @Schema(description = "")
  public Integer getCurrentPage() {
    return currentPage;
  }

  public void setCurrentPage(Integer currentPage) {
    this.currentPage = currentPage;
  }

  public PaginationSummary totalCerts(Long totalCerts) {
    this.totalCerts = totalCerts;
    return this;
  }

   /**
   * Get totalCerts
   * @return totalCerts
  **/
  @Schema(description = "")
  public Long getTotalCerts() {
    return totalCerts;
  }

  public void setTotalCerts(Long totalCerts) {
    this.totalCerts = totalCerts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaginationSummary paginationSummary = (PaginationSummary) o;
    return Objects.equals(this.pageSize, paginationSummary.pageSize) &&
        Objects.equals(this.currentPage, paginationSummary.currentPage) &&
        Objects.equals(this.totalCerts, paginationSummary.totalCerts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageSize, currentPage, totalCerts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaginationSummary {\n");

    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    currentPage: ").append(toIndentedString(currentPage)).append("\n");
    sb.append("    totalCerts: ").append(toIndentedString(totalCerts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
