/*
 * EJBCA REST Interface
 * API reference documentation.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.trustable.ca3s.core.service.dto.ejbca;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * PaginationRestResponseComponent
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-27T11:17:53.164838525Z[GMT]")

public class PaginationRestResponseComponent {
  @SerializedName("more_results")
  private Boolean moreResults = null;

  @SerializedName("next_offset")
  private Integer nextOffset = null;

  @SerializedName("number_of_results")
  private Integer numberOfResults = null;

  public PaginationRestResponseComponent moreResults(Boolean moreResults) {
    this.moreResults = moreResults;
    return this;
  }

   /**
   * Get moreResults
   * @return moreResults
  **/
  @Schema(description = "")
  public Boolean isMoreResults() {
    return moreResults;
  }

  public void setMoreResults(Boolean moreResults) {
    this.moreResults = moreResults;
  }

  public PaginationRestResponseComponent nextOffset(Integer nextOffset) {
    this.nextOffset = nextOffset;
    return this;
  }

   /**
   * Get nextOffset
   * @return nextOffset
  **/
  @Schema(description = "")
  public Integer getNextOffset() {
    return nextOffset;
  }

  public void setNextOffset(Integer nextOffset) {
    this.nextOffset = nextOffset;
  }

  public PaginationRestResponseComponent numberOfResults(Integer numberOfResults) {
    this.numberOfResults = numberOfResults;
    return this;
  }

   /**
   * Get numberOfResults
   * @return numberOfResults
  **/
  @Schema(description = "")
  public Integer getNumberOfResults() {
    return numberOfResults;
  }

  public void setNumberOfResults(Integer numberOfResults) {
    this.numberOfResults = numberOfResults;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaginationRestResponseComponent paginationRestResponseComponent = (PaginationRestResponseComponent) o;
    return Objects.equals(this.moreResults, paginationRestResponseComponent.moreResults) &&
        Objects.equals(this.nextOffset, paginationRestResponseComponent.nextOffset) &&
        Objects.equals(this.numberOfResults, paginationRestResponseComponent.numberOfResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(moreResults, nextOffset, numberOfResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaginationRestResponseComponent {\n");

    sb.append("    moreResults: ").append(toIndentedString(moreResults)).append("\n");
    sb.append("    nextOffset: ").append(toIndentedString(nextOffset)).append("\n");
    sb.append("    numberOfResults: ").append(toIndentedString(numberOfResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
