/*
 * EJBCA REST Interface
 * API reference documentation.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.trustable.ca3s.core.service.dto.ejbca;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * SearchCertificatesRestRequestV2
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-27T11:17:53.164838525Z[GMT]")

public class SearchCertificatesRestRequestV2 {
  @SerializedName("pagination")
  private Pagination pagination = null;

  @SerializedName("sort")
  private SearchCertificateSortRestRequest sort = null;

  @SerializedName("criteria")
  private List<SearchCertificateCriteriaRestRequest> criteria = null;

  public SearchCertificatesRestRequestV2 pagination(Pagination pagination) {
    this.pagination = pagination;
    return this;
  }

   /**
   * Get pagination
   * @return pagination
  **/
  @Schema(description = "")
  public Pagination getPagination() {
    return pagination;
  }

  public void setPagination(Pagination pagination) {
    this.pagination = pagination;
  }

  public SearchCertificatesRestRequestV2 sort(SearchCertificateSortRestRequest sort) {
    this.sort = sort;
    return this;
  }

   /**
   * Get sort
   * @return sort
  **/
  @Schema(description = "")
  public SearchCertificateSortRestRequest getSort() {
    return sort;
  }

  public void setSort(SearchCertificateSortRestRequest sort) {
    this.sort = sort;
  }

  public SearchCertificatesRestRequestV2 criteria(List<SearchCertificateCriteriaRestRequest> criteria) {
    this.criteria = criteria;
    return this;
  }

  public SearchCertificatesRestRequestV2 addCriteriaItem(SearchCertificateCriteriaRestRequest criteriaItem) {
    if (this.criteria == null) {
      this.criteria = new ArrayList<SearchCertificateCriteriaRestRequest>();
    }
    this.criteria.add(criteriaItem);
    return this;
  }

   /**
   * A List of search criteria.
   * @return criteria
  **/
  @Schema(description = "A List of search criteria.")
  public List<SearchCertificateCriteriaRestRequest> getCriteria() {
    return criteria;
  }

  public void setCriteria(List<SearchCertificateCriteriaRestRequest> criteria) {
    this.criteria = criteria;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchCertificatesRestRequestV2 searchCertificatesRestRequestV2 = (SearchCertificatesRestRequestV2) o;
    return Objects.equals(this.pagination, searchCertificatesRestRequestV2.pagination) &&
        Objects.equals(this.sort, searchCertificatesRestRequestV2.sort) &&
        Objects.equals(this.criteria, searchCertificatesRestRequestV2.criteria);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pagination, sort, criteria);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchCertificatesRestRequestV2 {\n");

    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    criteria: ").append(toIndentedString(criteria)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
