/*
 * EJBCA REST Interface
 * API reference documentation.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.trustable.ca3s.core.service.dto.ejbca;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * SearchCertificatesRestResponseV2
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-27T11:17:53.164838525Z[GMT]")

public class SearchCertificatesRestResponseV2 {
  @SerializedName("certificates")
  private List<CertificateRestResponseV2> certificates = null;

  @SerializedName("pagination_summary")
  private PaginationSummary paginationSummary = null;

  public SearchCertificatesRestResponseV2 certificates(List<CertificateRestResponseV2> certificates) {
    this.certificates = certificates;
    return this;
  }

  public SearchCertificatesRestResponseV2 addCertificatesItem(CertificateRestResponseV2 certificatesItem) {
    if (this.certificates == null) {
      this.certificates = new ArrayList<CertificateRestResponseV2>();
    }
    this.certificates.add(certificatesItem);
    return this;
  }

   /**
   * Get certificates
   * @return certificates
  **/
  @Schema(description = "")
  public List<CertificateRestResponseV2> getCertificates() {
    return certificates;
  }

  public void setCertificates(List<CertificateRestResponseV2> certificates) {
    this.certificates = certificates;
  }

  public SearchCertificatesRestResponseV2 paginationSummary(PaginationSummary paginationSummary) {
    this.paginationSummary = paginationSummary;
    return this;
  }

   /**
   * Get paginationSummary
   * @return paginationSummary
  **/
  @Schema(description = "")
  public PaginationSummary getPaginationSummary() {
    return paginationSummary;
  }

  public void setPaginationSummary(PaginationSummary paginationSummary) {
    this.paginationSummary = paginationSummary;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchCertificatesRestResponseV2 searchCertificatesRestResponseV2 = (SearchCertificatesRestResponseV2) o;
    return Objects.equals(this.certificates, searchCertificatesRestResponseV2.certificates) &&
        Objects.equals(this.paginationSummary, searchCertificatesRestResponseV2.paginationSummary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(certificates, paginationSummary);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchCertificatesRestResponseV2 {\n");

    sb.append("    certificates: ").append(toIndentedString(certificates)).append("\n");
    sb.append("    paginationSummary: ").append(toIndentedString(paginationSummary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
