package de.trustable.ca3s.core.service.util;

public class AuditUtil {

	public static final String AUDIT_CERTIFICATE_ACCEPTED = "CERTIFICATE_ACCEPTED";
	public static final String AUDIT_CERTIFICATE_REJECTED = "CERTIFICATE_REJECTED";
	public static final String AUDIT_WEB_CERTIFICATE_REQUESTED = "WEB_CERTIFICATE_REQUESTED";
	public static final String AUDIT_ACME_CERTIFICATE_REQUESTED = "ACME_CERTIFICATE_REQUESTED";
	public static final String AUDIT_ACME_CERTIFICATE_CREATED = "ACME_CERTIFICATE_CREATED";
	public static final String AUDIT_SCEP_CERTIFICATE_REQUESTED = "SCEP_CERTIFICATE_REQUESTED";
	public static final String AUDIT_SCEP_CERTIFICATE_CREATED = "SCEP_CERTIFICATE_CREATED";

}
