package de.trustable.ca3s.core.service.util;

public class AuditUtil {

	public static final String AUDIT_CSR_ACCEPTED = "CSR_ACCEPTED";
	public static final String AUDIT_CSR_REJECTED = "CSR_REJECTED";
	public static final String AUDIT_WEB_CERTIFICATE_REQUESTED = "WEB_CERTIFICATE_REQUESTED";
	public static final String AUDIT_ACME_CERTIFICATE_REQUESTED = "ACME_CERTIFICATE_REQUESTED";
	public static final String AUDIT_ACME_CERTIFICATE_CREATED = "ACME_CERTIFICATE_CREATED";
	public static final String AUDIT_SCEP_CERTIFICATE_REQUESTED = "SCEP_CERTIFICATE_REQUESTED";
	public static final String AUDIT_SCEP_CERTIFICATE_CREATED = "SCEP_CERTIFICATE_CREATED";
	public static final String AUDIT_CERTIFICATE_REVOKED = "CERTIFICATE_REVOKED";
	public static final String AUDIT_REQUEST_RESTRICTIONS_FAILED = "AUDIT_REQUEST_RESTRICTIONS_FAILED";
	public static final String AUDIT_WEB_CERTIFICATE_CREATED = "AUDIT_WEB_CERTIFICATE_CREATED";

}
